### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DomKalinowski** [nsmryan/zig_sealed_and_compact#6]
Hi @nsmryan, I've been wondering if you could add a license to this project. I'd like to make some improvements, but I don't want to infringe any copyright.

**Comment by nsmryan** [comment]
Yes, I can do that. I will have to work out an issue with my github account, but after that I will either use the MIT license or just make it public domain to make things easy (with a note asking for some kind of attribution if the library is used).

**Comment by DomKalinowski** [comment]
Amazing, thank you 🙏

**Comment by nsmryan** [comment]
I totally forgot about all of this until today. I just added a license file marking this library with CC0 to avoid any issue with re-use you might have. I'm interested to know how it is used, and if it helps anyone, but I don't want to create any friction in using the library.
